apiVersion: v1
kind: Pod
metadata:
  name: app
spec:
  containers:
    - name: ctrl
      image: alpine:latest
      command: ["sleep", "infinity"]
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /etc/name
          name: vomap
  volumes:
    - name: vomap
      configMap:
        name: multimap
