apiVersion: v1
kind: Pod
metadata:
  name: app_2
spec:
  containers:
    - name: ctrl
      image: alpine:latest
      command: ["sleep", "infinity"]  # Keeps the container running for debugging
      stdin: true
      tty: true
      volumeMounts:
        - mountPath: /etc/name
          name: test-config
  volumes:
    - name: test-config
      configMap:
        name: test-config

